### ISSUE TITLE
Unable to locate /path_to/sprue-0.0.1-SNAPSHOT-jar-with-dependencies.jar

### ISSUE THREAD

**Issue by siddarthkotnala** [mganta/sprue#1]
Hi I am not sure where to find this jar. Is it a part of Spark or Drool. From where can I download this jar?

**Comment by siddarthkotnala** [comment]
When I am running mvn clean package, I am getting the following error. Not sure if this is due to sprue jar.
![image](https://cloud.githubusercontent.com/assets/8197665/21635738/4c897ff0-d29a-11e6-99e6-fc3e7f273383.png)

![image](https://cloud.githubusercontent.com/assets/8197665/21635708/26c8fe4e-d29a-11e6-8597-3946b8d8323c.png)

**Comment by mganta** [comment]
delete your .pom file reference above and try to compile again.
